### ISSUE TITLE
Create unsaved file when project generation is off

### ISSUE THREAD

**Issue by frankhaugen** [sentryone/unittestgenerator#23]
When generating a test, (right-clicking on a class-file in the Solution Explorer), if autogeneration of a project is turned off, the tests should be generated to an unsaved file, (or other behaviour that isn't an error message that there is no project with the correct naming convention

**Comment by mattwhitfield** [comment]
Interesting idea.

How would you see it notifying people that they don't have a project with the correct naming convention? I wouldn't like for people to think that the extension was supposed to just create unsaved files...

Do you thing a comment banner at the top of the file explaining it would work in that instance?

**Comment by frankhaugen** [comment]
> How would you see it notifying people that they don't have a project with the correct naming convention? I wouldn't like for people to think that the extension was supposed to just create unsaved files... Something as simple as a pop-up?

A: Create the file, then messagebox with just a message
B: Show a messagebox with "yes/no" and ask if they want to create it and save it themselves
> Do you thing a comment banner at the top of the file explaining it would work in that instance?

I'm no fan of comments, but in this case it would be sensible, (and at the same time you should add a small snippet with "these tests were generated using SentryOne Unit Test Generator. URL: github.com/...")

**Comment by frankhaugen** [comment]
Actually, there's a lot of inspiration to be gleamed from the "Unit Test Boilerplate Generator"-extension, which I don't like after coming across Sentryone Test Generator, as it has good settings options, but there's very limited amounts of tests being generated

**Comment by mattwhitfield** [comment]
I quite like option B. 

I haven't done anything with adding a document that isn't associated with a project in any of the VS Extensions I've worked on, so I need to spend a while looking at how to do that. Thanks for the idea / input - it's very much appreciated!

**Comment by mattwhitfield** [comment]
So I implemented this as an option which defaults to enabled - such that it will open the file if there isn't a target project and the 'auto generate projects' option is off, with a banner at the top.

It's not 100% as I would like it. It generates the file in %temp% and then uses ItemOperations.OpenFile to open the file, then deletes the file on disk and marks it as unsaved. The only problem is that when you say 'yes' you would like to save it, it just saves it back to disk in %temp% instead of asking you where. Where this is a side project I don't have a huge amount of time to look into the APIs that Visual Studio Extensibility offers to enable a better experience here. However, I do think what I have implemented in #25 is definitely an improvement over the previous behavior. Thanks again for the suggestions.

**Comment by frankhaugen** [comment]
Great! There might be a way to set file properties to "read only", or something else. But for now, I'm really happy with the changes.

I might have a look at it myself if I find some time to really get into the nitty-gritty of the VS extension APIs

**Comment by mattwhitfield** [comment]
Many thanks! I'll close this issue for now - if you have any other ideas / comments please do feel free to open another.
